### ISSUE TITLE
CTL filter results

### ISSUE THREAD

**Issue by nickdrozd** [sligocki/busy-beaver#6]
I finally got around to trying out the CTL filter. I'm not sure if I'm using it right, but I ran it against my list of 11,702 4-state 2-color holdouts, and it failed on just 8 of them:

```
1RB 0LA  1LC 0RB  1RD 1LD  1LA 1RC
1RB 0LA  1LC 1RC  1RD 1LB  1LA 0RD
1RB 0LC  1LC 1RD  1LA 1LC  0LB 0RD
1RB 0LC  1LD 1RC  0LB 0RC  1LA 1LD
1RB 1LC  0LA 0RB  1RA 1RD  0LC 1LD
1RB 1LC  0RC 0LC  1LD 1RA  0RA 0LD
1RB 1RC  0LC 1LB  1RD 1LA  0LA 0RD
1RB 1RC  1LC 0LB  1RD 1LA  0RD 0LA
```

It's definitely possible that I'm misinterpreting things, but this list is somewhat interesting in any case. In particular the first program there is nifty. It sets up bound markers on either side of the head and gradually pushes them out.

Do you get similar results?

**Comment by sligocki** [comment]
Interestingly, I also have 8 4x2 holdouts remaining, but looks like a different list:
```
1RB1RA_1LC1RZ_0RA0LD_0RB0LC
1RB0RB_1LC1RB_1RZ0LD_1RA1LD
1RB0LD_1LC1RA_0RB0LC_1RZ1LA
1RB1RZ_0LC1RA_0RA1LD_0RB0LD
1RB1RZ_0LC0RD_1LA1LC_0LA0RB
1RB1LC_0LC1RD_1RZ1LA_0LA0RD
1RB1LA_1LA0RC_1LD1RC_1RZ0LA
1RB1LA_0LA1RC_1LD0RB_1RZ1LC
1RB1LA_0LA1RC_1RA1RD_1RZ0RB
```
