### ISSUE TITLE
`RecursionError` in `struct_eq`

### ISSUE THREAD

**Issue by nickdrozd** [sligocki/busy-beaver#7]
`Code/Quick_Sim.py -r --exp-linear-rules --no-steps <(echo 1RB2RB3LA2RA3RA_0LA1RB4RA1LB1RZ)`

**Comment by sligocki** [comment]
Yeah, this is sort of working as intended. This has run too deep but can't prove anything. You can set python recursive depth deeper if you like. Someday I might make the error more user friendly.

**Comment by sligocki** [comment]
The python command is `sys.setrecursionlimit(10_000)` by the way ... not sure what the downside is of expanding this so much, heh.

**Comment by nickdrozd** [comment]
I increased the recursion limit and then it hit some other kind of depth limit. So is it safe to assume that this is an infinite rule? Or is there any reason to believe it will terminate?

**Comment by sligocki** [comment]
Well, it's definitely not safe! But I do assume it's infinite :) Really all it says is that my system cannot yet tell you. It's roughly equivalent to saying it ran for too many steps and we gave up.
