### ISSUE TITLE
Exp int exception

### ISSUE THREAD

**Issue by nickdrozd** [sligocki/busy-beaver#8]
Running program `1RB---_1LC0RB_1LD0RD_0RE1LB_0RC1RF_0RA1RE`:

```
Code/Quick_Sim.py -r --exp-linear-rules <(echo 1RB---_1LC0RB_1LD0RD_0RE1LB_0RC1RF_0RA1RE)
```

Raises exception:

```
Exp_Int.ExpIntException: Cannot evalulate sign of ExpInt: ((12096 + -2576 * 6^((1 + 69 * 6^((-4 + 69 * 6^((-4 + 69 * 6^13)/5))/5))/5) + 2116 * 6^((-3 + 23 * 6^((1 + 69 * 6^((-4 + 69 * 6^13)/5))/5))/5) + -46 * 6^((11 + 69 * 6^((-4 + 69 * 6^((-4 + 69 * 6^13)/5))/5))/5))/25)    ((3, 140252096236.63162) == (3, 140252096236.63162))
```

I think it's infinite, but not 100% sure. Running with `--no-steps` raises no error and seems to run without stopping.

**Comment by sligocki** [comment]
Yeah, this is sort of "working as intended". In general using `--exp-linear-rules` without `--no-steps` is a little tricky. Normalization for these exponential formulas is not easy and this is one of the failure modes (where it cannot figure out the sign of the formula). I think eventually I'd like to improve this a bit, but it's not high priority for now. I suggest using `--no-steps` liberally for these big machines.
